### ISSUE TITLE
US1: User account creation

### ISSUE THREAD

**Issue by mconnors55** [mconnors55/PowerPlate#21]

**Comment by jdambrosca** [comment]
# USER STORY: User Account Creation

**AS A** new user who wants to join the PowerPlate app,  
**INSTEAD OF** filling out long registration forms,  
**I WANT TO** create an account using my Google account **IN** a few seconds,  
**SO THAT** I can quickly start tracking my meals and protein intake without hassle.

### SCENARIO 1: Successful account creation with Google

**GIVEN** the user has a Google account,  
**WHEN** the user clicks the "Sign Up with Google" button,  
**AND** successfully provides valid credentials via the Google login prompt,  
**THEN** the user’s new PowerPlate account is created,  
**AND** they are redirected to the homepage **WITHIN 2 seconds**,  
**WHERE** the app shows a welcome message and prompts them to set up their meal tracking.

### SCENARIO 2: User already logged into Google account

**GIVEN** the user is already logged into their Google account on their device,  
**WHEN** the user opens the PowerPlate app and selects "Sign Up with Google",  
**THEN** the account is created automatically without needing to re-enter credentials **WITHIN 1 second**,  
**AND** they are redirected to the homepage **WITHIN 2 seconds** where a welcome message is displayed.

### SCENARIO 3: Google account creation fails due to existing account

**GIVEN** the user already has a PowerPlate account linked to their Google account,  
**WHEN** they attempt to sign up using the same Google account,  
**THEN** the app displays an error message informing them the account already exists **WITHIN 1 second**  
**AND** provides an option to log in instead.
